# syntax = docker/dockerfile:1
# escape=`

ARG DOCKER_REGISTRY
FROM ${DOCKER_REGISTRY}/woodpecker-windows-base:latest

LABEL architecture="x86_64" `
      maintainer="Geco-iT Team <contact@geco-it.fr>" `
      name="geco-it/woodpecker-windows-r" `
      vendor="Geco-iT"

SHELL ["cmd", "/S", "/C"]

# Install Last R Project (add choco install rtools ??)
RUN choco install -y r.project --params "/AddToPath" && `
    rmdir /S /Q C:\tmp\cache

SHELL ["bash.exe", "-c"]

ENTRYPOINT ["bash.exe"]
