# syntax = docker/dockerfile:1
# escape=`

ARG DOCKER_REGISTRY
FROM ${DOCKER_REGISTRY}/woodpecker-windows-base-chocolatey:latest

SHELL ["powershell", "-noprofile", "-noninteractive", "-command"]

RUN choco install -y caddy

USER ContainerUser

WORKDIR C:\woodpecker

EXPOSE 80

ENTRYPOINT ["caddy.exe", "file-server", "-r", "."]

