---
labels:
  platform: linux/amd64
  backend: docker

when:
  event:
    - tag

depends_on:
  - lint
  - windows-build-and-push

skip_clone: true

matrix:
  include:
    - image: woodpecker-agent
      version: v3.0.1
    - image: woodpecker-git-plugin
      version: latest
    - image: woodpecker-windows-base
      version: latest
    - image: woodpecker-windows-base-chocolatey
      version: latest
    - image: woodpecker-windows-base-chocolatey-msvsbuild
      version: latest
    - image: woodpecker-windows-python
      version: 3.10
    - image: woodpecker-windows-python
      version: 3.11
    - image: woodpecker-windows-python
      version: 3.12
    - image: woodpecker-windows-python
      version: 3.13

steps:
  - name: Add 'docker-hub' label
    image: ${DOCKER_INTERNAL_REGISTRY}/${CI_REPO_OWNER,,}/woodpecker-harbor-label-plugin
    pull: true
    settings:
      registry:
        from_secret: DOCKER_REGISTRY
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASSWORD
      debug: true
      label: docker-hub
      project: ${CI_REPO_OWNER,,}
      image: ${image}
      tag: "${version}"
