---
labels:
  platform: windows/amd64
  backend: local

depends_on:
  - lint

matrix:
  image:
    - base
    - python-3.12
    - python-3.11
    - python-3.10
    - r-project

steps:
  - name: configure
    image: bash.exe
    environment:
      DOCKER_REGISTRY:
        from_secret: DOCKER_REGISTRY
    commands:
      - cd ./build
      - cp .env.sample .env
      - sed -e "s;^DOCKER_REGISTRY=.*;DOCKER_REGISTRY=$${DOCKER_REGISTRY}/${CI_REPO_OWNER,,};" -i .env
    when:
      event: push

  - name: configure
    image: bash.exe
    environment:
      DOCKER_REGISTRY:
        from_secret: DOCKER_REGISTRY
      DOCKER_REGISTRY_USERNAME:
        from_secret: DOCKER_REGISTRY_USERNAME
      DOCKER_REGISTRY_PASSWORD:
        from_secret: DOCKER_REGISTRY_PASSWORD
    commands:
      - cd ./build
      - cp .env.sample .env
      - sed -e "s;^DOCKER_REGISTRY=.*;DOCKER_REGISTRY=$${DOCKER_REGISTRY}/${CI_REPO_OWNER,,};" -i .env
      - echo "$${DOCKER_REGISTRY_PASSWORD}" | docker login $${DOCKER_REGISTRY} --username $${DOCKER_REGISTRY_USERNAME} --password-stdin
    when:
      event: tag

  - name: build
    image: bash.exe
    commands:
      - cd ./build
      - docker-compose build ${image} --memory 2GB
    when:
      event: [push, tag]

  - name: push
    image: bash.exe
    commands:
      - cd ./build
      - docker-compose push ${image}
    when:
      event: tag
